name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      minio:
        image: ghcr.io/${{ github.repository }}:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: testuser
          MINIO_ROOT_PASSWORD: testpass123

    steps:
      - name: Test MinIO
        run: |
          sleep 10
          curl -f http://localhost:9000/minio/health/live

          wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set local http://localhost:9000 testuser testpass123
          ./mc mb local/test-bucket
          ./mc ls local/

          echo "test content" > test.txt
          ./mc cp test.txt local/test-bucket/
          ./mc cp local/test-bucket/test.txt downloaded.txt
          cat downloaded.txt
